### ISSUE TITLE
模拟宇宙无法进入

### ISSUE THREAD

**Issue by ubbhnn** [gucooing/hkrpg-go-public#4]
模拟宇宙无法进入
![Screenshot_2024-07-29-03-07-21-60_ccfddf37bac95b1](https://github.com/user-attachments/assets/3655402b-7933-4152-adfe-b65aa16c1a72)

**Comment by gucooing** [comment]
你需要在数据库中填写模拟宇宙期数

**Comment by ubbhnn** [comment]
好的谢谢
