### ISSUE TITLE
2.4版本无法进来游戏

### ISSUE THREAD

**Issue by ubbhnn** [gucooing/hkrpg-go-public#5]
![123549168b9f70f87aa4c1d18680c937](https://github.com/user-attachments/assets/04e88e79-f130-4847-8cc4-608f3eeab910)

**Comment by gucooing** [comment]
用的是pe还是分体？

**Comment by ubbhnn** [comment]
> 用的是pe还是分体？

分体的

**Comment by gucooing** [comment]
gameserver是怎么报错的？

**Comment by gucooing** [comment]
[ERROR][0m [31mnodeserver error:dial tcp 127.0.0.1:20081: connectex: No connection could be made because the target machine actively refused it. 没有连接到nodeserver

**Comment by gucooing** [comment]
还有，res先不需要覆盖，还没上传2.4的config

**Comment by ubbhnn** [comment]
> 还有，res先不需要覆盖，还没上传2.4的config

好的  那就是没有剧情暂时
